### ISSUE TITLE
React dropzone as a dependency

### ISSUE THREAD

**Issue by okpatil4u** [praneybehl/meteor-react-disqus-comments#1]
You should add react dropzone as a dependency

**Comment by okpatil4u** [comment]
While processing files with cosmos:browserify (for target web.browser):
   packages/praneybehl:react-disqus-comments/package.browserify.js: Cannot find
   module 'react-dropzone' from

**Comment by praneybehl** [comment]
It doesn't need react-dropzone as dependency. Not sure why the error and meteor would not let me rebuild the package.
So I had to unpublish the package and republish it with another name.
Please use the package with the new name : 

``` JS
meteor add praneybehl:reactjs-disqus-comments
```

Its working fine now, please let me know how you go with it.

**Comment by praneybehl** [comment]
I am closing since its working fine my end and no response from you
